// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gonjecjssahhrgusnonv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbmplY2pzc2FoaHJndXNub252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTU4MDUsImV4cCI6MjA2MzE3MTgwNX0.iG0FyoxYD1F-kO4_nrlmCaSXvNG4drlgBFHN9YDpeiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);